require("colorbuddy").colorscheme("subliminal_next")

local colorbuddy = require("colorbuddy")
local Color = colorbuddy.Color
local Group = colorbuddy.Group
local c = colorbuddy.colors
local g = colorbuddy.groups
local s = colorbuddy.styles

-- Palette
Color.new("bg", "#232830")
Color.new("bg_alt", "#262C35")
Color.new("bg_input", "#1D2228")
Color.new("bg_panel", "#252A33")
Color.new("bg_border", "#2C313C")
Color.new("bg_hover", "#2c313a")
Color.new("bg_selection", "#3D4556")
Color.new("bg_highlight", "#484e5b")
Color.new("bg_word", "#314365")

Color.new("fg", "#d4d4d4")
Color.new("fg_dim", "#8EA1B3")
Color.new("fg_muted", "#9da5b4")
Color.new("fg_alt", "#c0c5cd")
Color.new("fg_linenr", "#3B4048")
Color.new("fg_linenr_active", "#72777F")
Color.new("cursor", "#b6bcc4")

Color.new("red", "#FFA5C3")
Color.new("red_error", "#E15A60")
Color.new("yellow", "#FFDFA5")
Color.new("green", "#95E5A6")
Color.new("green_subtle", "#99C794")
Color.new("blue", "#8CD8D8")
Color.new("purple", "#BB80B3")
Color.new("orange", "#AB7967")
Color.new("gray", "#7f7f7f")

Color.new("comment", "#808890")
Color.new("nontext", "#505762")

-- UI Groups
Group.new("Normal", c.fg, c.bg)
Group.new("NormalFloat", c.fg, c.bg_alt)
Group.new("FloatBorder", c.bg_border, c.bg_alt)

Group.new("Visual", nil, c.bg_selection)
Group.new("VisualNOS", nil, c.bg_selection)

Group.new("Search", c.bg, c.yellow)
Group.new("IncSearch", c.bg, c.yellow)
Group.new("CurSearch", g.Search, g.Search)
Group.new("Substitute", g.IncSearch, g.IncSearch)

Group.new("Cursor", c.cursor, nil)
Group.new("lCursor", g.Cursor, g.Cursor)
Group.new("CursorIM", g.Cursor, g.Cursor)

Group.new("CursorLine", nil, c.bg)
Group.new("CursorColumn", nil, c.bg)

Group.new("LineNr", c.fg_linenr, nil)
Group.new("CursorLineNr", c.fg_linenr_active, nil)
Group.new("CursorLineFold", g.LineNr, g.LineNr)
Group.new("CursorLineSign", g.LineNr, g.LineNr)

Group.new("ColorColumn", nil, c.bg_highlight)

Group.new("SignColumn", nil, c.bg)
Group.new("FoldColumn", nil, c.bg)
Group.new("Folded", c.fg_dim, c.bg_alt)

Group.new("VertSplit", c.bg_border, c.bg)
Group.new("WinSeparator", c.bg_border, c.bg)

Group.new("TabLine", c.fg_dim, c.bg_alt)
Group.new("TabLineSel", c.fg, c.bg)
Group.new("TabLineFill", nil, c.bg_alt)

Group.new("StatusLine", c.fg, c.bg_alt)
Group.new("StatusLineNC", c.fg_dim, c.bg_alt)
Group.new("StatusLineTerm", g.StatusLine, g.StatusLine)
Group.new("StatusLineTermNC", g.StatusLineNC, g.StatusLineNC)

Group.new("WildMenu", g.Normal, g.Normal)
Group.new("Directory", c.blue, nil)

Group.new("Pmenu", c.fg, c.bg_input)
Group.new("PmenuSel", c.fg, c.bg_hover)
Group.new("PmenuSbar", nil, c.bg_panel)
Group.new("PmenuThumb", nil, c.bg_border)

Group.new("Question", c.green, nil)
Group.new("Title", c.yellow, nil)
Group.new("ModeMsg", c.fg, nil)
Group.new("MoreMsg", c.green, nil)

Group.new("ErrorMsg", c.red_error, nil)
Group.new("WarningMsg", c.yellow, nil)

Group.new("MatchParen", nil, c.bg_highlight)
Group.new("Conceal", c.fg_dim, nil)

Group.new("SpellBad", c.red_error, nil, s.undercurl)
Group.new("SpellCap", c.yellow, nil, s.undercurl)
Group.new("SpellLocal", c.blue, nil, s.undercurl)
Group.new("SpellRare", c.purple, nil, s.undercurl)

Group.new("SpecialKey", c.nontext, nil)
Group.new("NonText", c.nontext, nil)
Group.new("Whitespace", c.nontext, nil)

Group.new("DiagnosticError", c.red_error, nil)
Group.new("DiagnosticWarn", c.yellow, nil)
Group.new("DiagnosticInfo", c.blue, nil)
Group.new("DiagnosticHint", c.gray, nil)
Group.new("DiagnosticOk", c.green, nil)
Group.new("DiagnosticUnderlineError", nil, nil, s.undercurl)
Group.new("DiagnosticUnderlineWarn", nil, nil, s.undercurl)
Group.new("DiagnosticUnderlineInfo", nil, nil, s.undercurl)
Group.new("DiagnosticUnderlineHint", nil, nil, s.undercurl)
Group.new("DiagnosticUnderlineOk", nil, nil, s.undercurl)
Group.new("DiagnosticVirtualTextError", c.red_error, c.bg_panel)
Group.new("DiagnosticVirtualTextWarn", c.yellow, c.bg_panel)
Group.new("DiagnosticVirtualTextInfo", c.blue, c.bg_panel)
Group.new("DiagnosticVirtualTextHint", c.gray, c.bg_panel)
Group.new("DiagnosticFloatingError", c.red_error, nil)
Group.new("DiagnosticFloatingWarn", c.yellow, nil)
Group.new("DiagnosticFloatingInfo", c.blue, nil)
Group.new("DiagnosticFloatingHint", c.gray, nil)
Group.new("DiagnosticSignError", c.red_error, nil)
Group.new("DiagnosticSignWarn", c.yellow, nil)
Group.new("DiagnosticSignInfo", c.blue, nil)
Group.new("DiagnosticSignHint", c.gray, nil)

Group.new("LspReferenceText", nil, c.bg_selection)
Group.new("LspReferenceRead", nil, c.bg_selection)
Group.new("LspReferenceWrite", nil, c.bg_selection)
Group.new("LspCodeLens", c.fg_dim, nil)
Group.new("LspCodeLensSeparator", c.fg_dim, nil)
Group.new("LspSignatureActiveParameter", nil, c.bg_highlight)

Group.new("DiffAdd", c.green_subtle, nil)
Group.new("DiffChange", c.blue, nil)
Group.new("DiffDelete", c.red_error, nil)
Group.new("DiffText", c.blue, nil)

-- Treesitter
Group.new("@comment", c.comment, nil, s.italic)
Group.new("@error", c.red_error, nil)
Group.new("@none", c.fg, nil)
Group.new("@preproc", c.gray, nil)
Group.new("@define", c.gray, nil)
Group.new("@operator", c.yellow, nil)

Group.new("@punctuation.delimiter", c.gray, nil)
Group.new("@punctuation.bracket", c.gray, nil)
Group.new("@punctuation.special", c.gray, nil)

Group.new("@string", c.green, nil)
Group.new("@string.escape", c.blue, nil)
Group.new("@string.regex", c.blue, nil)
Group.new("@string.special", c.green_subtle, nil)

Group.new("@character", c.green, nil)
Group.new("@character.special", c.blue, nil)

Group.new("@boolean", c.blue, nil)
Group.new("@number", c.blue, nil)
Group.new("@float", c.blue, nil)

Group.new("@function", c.red, nil)
Group.new("@function.builtin", c.yellow, nil)
Group.new("@function.call", c.yellow, nil)
Group.new("@function.macro", c.red, nil)
Group.new("@method", c.red, nil)
Group.new("@method.call", c.yellow, nil)
Group.new("@constructor", c.yellow, nil)

Group.new("@conditional", c.gray, nil)
Group.new("@repeat", c.gray, nil)
Group.new("@label", c.fg, nil)
Group.new("@include", c.gray, nil)
Group.new("@exception", c.red_error, nil)

Group.new("@keyword", c.gray, nil)
Group.new("@keyword.function", c.gray, nil)
Group.new("@keyword.operator", c.yellow, nil)
Group.new("@keyword.return", c.red, nil)

Group.new("@operator", c.yellow, nil)

Group.new("@attribute", c.yellow, nil, s.italic)
Group.new("@property", c.fg, nil)

Group.new("@tag", c.gray, nil)
Group.new("@tag.attribute", c.fg, nil, s.italic)
Group.new("@tag.delimiter", c.gray, nil)

Group.new("@type", c.blue, nil, s.underline)
Group.new("@type.builtin", c.blue, nil, s.italic)
Group.new("@type.definition", c.blue, nil, s.underline)
Group.new("@type.qualifier", c.gray, nil)

Group.new("@variable", c.fg, nil)
Group.new("@variable.builtin", c.fg, nil)
Group.new("@variable.member", c.fg, nil)
Group.new("@variable.parameter", c.fg, nil)

Group.new("@constant", c.blue, nil)
Group.new("@constant.builtin", c.blue, nil)
Group.new("@constant.macro", c.blue, nil)

Group.new("@markup.strong", nil, nil, s.bold)
Group.new("@markup.italic", nil, nil, s.italic)
Group.new("@markup.strikethrough", nil, nil, s.strikethrough)
Group.new("@markup.underline", nil, nil, s.underline)
Group.new("@markup.heading", c.blue, nil, s.bold)
Group.new("@markup.raw", c.green, nil)
Group.new("@markup.link", c.blue, nil, s.underline)
Group.new("@markup.link.url", c.blue, nil, s.underline)
Group.new("@markup.list", c.gray, nil)
Group.new("@markup.quote", c.gray, nil)
Group.new("@markup.math", c.blue, nil)
Group.new("@markup.environment", c.blue, nil)

Group.new("@diff.plus", c.green_subtle, nil)
Group.new("@diff.minus", c.red_error, nil)
Group.new("@diff.delta", c.blue, nil)

Group.new("@module", c.fg, nil)
Group.new("@namespace", c.fg, nil)
Group.new("@symbol", c.blue, nil)
Group.new("@identifier", c.fg, nil)

-- LazyVim additional
Group.new("DashboardHeader", c.blue, nil, s.bold)
Group.new("DashboardIcon", c.blue, nil)
Group.new("DashboardDesc", c.green, nil)
Group.new("DashboardKey", c.yellow, nil)
Group.new("DashboardFooter", c.fg_dim, nil)
Group.new("DashboardShortcut", c.blue, nil)
Group.new("DashboardProjectTitle", c.fg, nil)
Group.new("DashboardProjectTitleIcon", c.yellow, nil)
Group.new("DashboardProjectFileIcon", c.blue, nil)
Group.new("DashboardMruTitle", c.fg, nil)
Group.new("DashboardMruIcon", c.blue, nil)

-- Lazy
Group.new("LazyButton", c.fg, c.bg_border)
Group.new("LazyButtonActive", c.bg, c.yellow)
Group.new("LazyComment", c.comment, nil)
Group.new("LazyCommit", c.blue, nil)
Group.new("LazyCommitIssue", c.red, nil)
Group.new("LazyDimmed", c.fg_dim, nil)
Group.new("LazyDir", c.blue, nil)
Group.new("LazyH1", c.blue, c.bg_panel, s.bold)
Group.new("LazyH2", c.yellow, c.bg_panel, s.bold)
Group.new("LazyIdentifier", c.blue, nil)
Group.new("LazyPerLine", c.fg_dim, nil)
Group.new("LazyProp", c.fg_muted, nil)
Group.new("LazyReasonCmd", c.blue, nil)
Group.new("LazyReasonEvent", c.green, nil)
Group.new("LazyReasonFt", c.yellow, nil)
Group.new("LazyReasonImport", c.blue, nil)
Group.new("LazyReasonKeys", c.orange, nil)
Group.new("LazyReasonPlugin", c.gray, nil)
Group.new("LazyReasonRuntime", c.comment, nil)
Group.new("LazyReasonSource", c.blue, nil)
Group.new("LazyReasonStart", c.green, nil)
Group.new("LazySpecial", c.blue, nil)
Group.new("LazyTaskOutput", c.fg, nil)
Group.new("LazyUrl", c.blue, nil, s.underline)

Group.new("GitSignsAdd", c.green, nil)
Group.new("GitSignsChange", c.blue, nil)
Group.new("GitSignsDelete", c.red_error, nil)
Group.new("GitSignsAddNr", c.green, nil)
Group.new("GitSignsChangeNr", c.blue, nil)
Group.new("GitSignsDeleteNr", c.red_error, nil)
Group.new("GitSignsAddLn", c.green, nil)
Group.new("GitSignsChangeLn", c.blue, nil)
Group.new("GitSignsDeleteLn", c.red_error, nil)

Group.new("MiniIndentscopeSymbol", c.nontext, nil)
Group.new("MiniIndentscopeSymbolOff", c.bg, nil)

-- Notify
Group.new("NotifyDEBUGBody", c.fg_dim, c.bg_alt)
Group.new("NotifyDEBUGBorder", c.gray, nil)
Group.new("NotifyDEBUGIcon", c.gray, nil)
Group.new("NotifyDEBUGTitle", c.gray, nil)
Group.new("NotifyERRORBody", c.fg, c.bg_alt)
Group.new("NotifyERRORBorder", c.red_error, nil)
Group.new("NotifyERRORIcon", c.red_error, nil)
Group.new("NotifyERRORTitle", c.red_error, nil)
Group.new("NotifyINFOBody", c.fg, c.bg_alt)
Group.new("NotifyINFOBorder", c.blue, nil)
Group.new("NotifyINFOIcon", c.blue, nil)
Group.new("NotifyINFOTitle", c.blue, nil)
Group.new("NotifyTRACEBody", c.fg_dim, c.bg_alt)
Group.new("NotifyTRACEBorder", c.purple, nil)
Group.new("NotifyTRACEIcon", c.purple, nil)
Group.new("NotifyTRACETitle", c.purple, nil)
Group.new("NotifyWARNBody", c.fg, c.bg_alt)
Group.new("NotifyWARNBorder", c.yellow, nil)
Group.new("NotifyWARNIcon", c.yellow, nil)
Group.new("NotifyWARNTitle", c.yellow, nil)

-- NvimTree
Group.new("NvimTreeNormal", c.fg, c.bg_alt)
Group.new("NvimTreeRootFolder", c.blue:light(), nil, s.bold)
Group.new("NvimTreeGitDirty", c.blue, nil)
Group.new("NvimTreeGitNew", c.green, nil)
Group.new("NvimTreeGitDeleted", c.red_error, nil)
Group.new("NvimTreeSpecialFile", c.yellow, nil)
Group.new("NvimTreeFolderName", c.blue:light(), nil)
Group.new("NvimTreeEmptyFolderName", c.fg, nil)
Group.new("NvimTreeOpenedFolderName", c.blue:light(), nil, s.italic)
Group.new("NvimTreeIndentMarker", c.nontext, nil)
Group.new("NvimTreeImageFile", c.fg_muted, nil)
Group.new("NvimTreeSymlink", c.blue, nil, s.italic)
Group.new("NvimTreeExecFile", c.green, nil)

-- WhichKey
Group.new("WhichKey", c.blue, nil, s.bold)
Group.new("WhichKeyGroup", c.yellow, nil, s.bold)
Group.new("WhichKeyDesc", c.fg, nil)
Group.new("WhichKeySeperator", c.gray, nil)
Group.new("WhichKeyFloat", nil, c.bg_alt)
Group.new("WhichKeyValue", c.green, nil)

-- Telescope
Group.new("TelescopeNormal", c.fg, c.bg_alt)
Group.new("TelescopeBorder", c.bg_border, c.bg_alt)
Group.new("TelescopeTitle", c.fg, nil, s.bold)
Group.new("TelescopePromptNormal", c.fg, c.bg_input)
Group.new("TelescopePromptBorder", c.bg_border, c.bg_input)
Group.new("TelescopePromptTitle", c.fg, c.bg_input, s.bold)
Group.new("TelescopeResultsTitle", c.fg_dim, nil)
Group.new("TelescopePreviewTitle", c.fg_dim, nil)
Group.new("TelescopeSelection", nil, c.bg_selection)
Group.new("TelescopeSelectionCaret", c.yellow, nil)
Group.new("TelescopeMultiSelection", nil, c.bg_selection)
Group.new("TelescopeMatching", c.yellow, nil)
Group.new("TelescopePromptPrefix", c.yellow, nil)

-- Noice
Group.link("NoiceCmdlinePopup", g.NormalFloat)
Group.link("NoiceCmdlinePopupBorder", g.FloatBorder)
Group.new("NoiceCmdlineIcon", c.yellow, nil)
Group.link("NoicePopupmenu", g.Pmenu)
Group.link("NoicePopupmenuBorder", g.FloatBorder)

-- Flash
Group.new("FlashLabel", c.bg, c.yellow, s.bold)
Group.new("FlashMatch", nil, c.bg_selection)
Group.new("FlashCurrent", nil, c.bg_selection)

-- Snacks
Group.new("SnacksIndentScope", c.nontext:light(), nil)
Group.new("SnacksIndentChunk", c.fg_dim, nil)

-- SmoothCursor
Group.new("SmoothCursor", c.cursor, nil)

-- IlluminatedWords
Group.new("IlluminatedWordText", nil, c.bg_selection)
Group.new("IlluminatedWordRead", nil, c.bg_selection)
Group.new("IlluminatedWordWrite", nil, c.bg_selection)

-- Hop / Sneak / EasyMotion
Group.new("HopNextKey", c.yellow, nil, s.bold)
Group.new("HopNextKey1", c.blue, nil, s.bold)
Group.new("HopNextKey2", c.fg_dim, nil)
Group.new("HopUnmatched", c.fg_dim, nil)

-- Neo-tree
Group.new("NeoTreeNormal", c.fg, c.bg_alt)
Group.new("NeoTreeRootName", c.blue:light(), nil, s.bold)
Group.new("NeoTreeGitAdded", c.green, nil)
Group.new("NeoTreeGitModified", c.blue, nil)
Group.new("NeoTreeGitDeleted", c.red_error, nil)
Group.new("NeoTreeGitUntracked", c.green, nil)
Group.new("NeoTreeIndentMarker", c.nontext, nil)
Group.new("NeoTreeSymbolicLinkTarget", c.blue, nil, s.italic)
Group.new("NeoTreeDimText", c.fg, nil)
Group.new("NeoTreeFloatNormal", c.fg, c.bg_alt)
Group.new("NeoTreeFloatBorder", c.bg_border, c.bg_alt)
Group.new("NeoTreeTitleBar", nil, c.bg_alt)

-- Cmp
Group.new("CmpItemAbbr", c.fg, nil)
Group.new("CmpItemAbbrDeprecated", c.fg_dim, nil, s.strikethrough)
Group.new("CmpItemAbbrMatch", c.yellow, nil)
Group.new("CmpItemAbbrMatchFuzzy", c.yellow, nil)
Group.new("CmpItemKind", c.blue, nil)
Group.new("CmpItemMenu", c.fg_dim, nil)
Group.new("CmpItemKindSnippet", c.red, nil)
Group.new("CmpItemKindKeyword", c.gray, nil)
Group.new("CmpItemKindText", c.green, nil)
Group.new("CmpItemKindMethod", c.blue, nil)
Group.new("CmpItemKindConstructor", c.yellow, nil)
Group.new("CmpItemKindFunction", c.red, nil)
Group.new("CmpItemKindFolder", c.blue, nil)
Group.new("CmpItemKindModule", c.fg, nil)
Group.new("CmpItemKindConstant", c.blue, nil)
Group.new("CmpItemKindField", c.fg, nil)
Group.new("CmpItemKindProperty", c.fg, nil)
Group.new("CmpItemKindEnum", c.blue, nil)
Group.new("CmpItemKindUnit", c.green, nil)
Group.new("CmpItemKindClass", c.yellow, nil)
Group.new("CmpItemKindVariable", c.fg, nil)
Group.new("CmpItemKindValue", c.blue, nil)
Group.new("CmpItemKindInterface", c.blue, nil)
Group.new("CmpItemKindColor", c.red, nil)
Group.new("CmpItemKindReference", c.blue, nil)
Group.new("CmpItemKindFile", c.blue, nil)
Group.new("CmpItemKindStruct", c.blue, nil)
Group.new("CmpItemKindEvent", c.yellow, nil)
Group.new("CmpItemKindOperator", c.yellow, nil)
Group.new("CmpItemKindTypeParameter", c.blue, nil)
Group.new("CmpItemKindCopilot", c.green, nil)
Group.new("CmpItemKindCodeium", c.green, nil)
Group.new("CmpItemKindSuperMaven", c.green, nil)
Group.new("CmpItemKindTabNine", c.green, nil)

-- Blink
Group.new("BlinkCmpDoc", c.fg, c.bg_alt)
Group.new("BlinkCmpDocBorder", c.bg_border, c.bg_alt)
Group.new("BlinkCmpMenu", c.fg, c.bg_alt)
Group.new("BlinkCmpMenuBorder", c.bg_border, c.bg_alt)
Group.new("BlinkCmpMenuSelection", nil, c.bg_hover)
Group.new("BlinkCmpScrollBarThumb", nil, c.bg_border)
Group.new("BlinkCmpScrollBarTrack", nil, c.bg_panel)
Group.link("BlinkCmpSource", g.CmpItemMenu)
Group.link("BlinkCmpLabel", g.CmpItemAbbr)
Group.link("BlinkCmpLabelDeprecated", g.CmpItemAbbrDeprecated)
Group.link("BlinkCmpLabelMatch", g.CmpItemAbbrMatch)
Group.link("BlinkCmpKindSnippet", g.CmpItemKindSnippet)
Group.link("BlinkCmpKindKeyword", g.CmpItemKindKeyword)
Group.link("BlinkCmpKindText", g.CmpItemKindText)
Group.link("BlinkCmpKindMethod", g.CmpItemKindMethod)
Group.link("BlinkCmpKindConstructor", g.CmpItemKindConstructor)
Group.link("BlinkCmpKindFunction", g.CmpItemKindFunction)
Group.link("BlinkCmpKindFolder", g.CmpItemKindFolder)
Group.link("BlinkCmpKindModule", g.CmpItemKindModule)
Group.link("BlinkCmpKindConstant", g.CmpItemKindConstant)
Group.link("BlinkCmpKindField", g.CmpItemKindField)
Group.link("BlinkCmpKindProperty", g.CmpItemKindProperty)
Group.link("BlinkCmpKindEnum", g.CmpItemKindEnum)
Group.link("BlinkCmpKindUnit", g.CmpItemKindUnit)
Group.link("BlinkCmpKindClass", g.CmpItemKindClass)
Group.link("BlinkCmpKindVariable", g.CmpItemKindVariable)
Group.link("BlinkCmpKindValue", g.CmpItemKindValue)
Group.link("BlinkCmpKindInterface", g.CmpItemKindInterface)
Group.link("BlinkCmpKindColor", g.CmpItemKindColor)
Group.link("BlinkCmpKindReference", g.CmpItemKindReference)
Group.link("BlinkCmpKindFile", g.CmpItemKindFile)
Group.link("BlinkCmpKindStruct", g.CmpItemKindStruct)
Group.link("BlinkCmpKindEvent", g.CmpItemKindEvent)
Group.link("BlinkCmpKindOperator", g.CmpItemKindOperator)
Group.link("BlinkCmpKindTypeParameter", g.CmpItemKindTypeParameter)
Group.link("BlinkCmpKindCopilot", g.CmpItemKindCopilot)

-- Semantic Tokens (LSP)
Group.new("@lsp.type.class", c.yellow, nil)
Group.new("@lsp.type.comment", c.comment, nil, s.italic)
Group.new("@lsp.type.decorator", c.yellow, nil, s.italic)
Group.new("@lsp.type.enum", c.blue, nil)
Group.new("@lsp.type.enumMember", c.blue, nil)
Group.new("@lsp.type.function", c.red, nil)
Group.new("@lsp.type.interface", c.blue, nil)
Group.new("@lsp.type.keyword", c.gray, nil)
Group.new("@lsp.type.macro", c.orange, nil)
Group.new("@lsp.type.method", c.red, nil)
Group.new("@lsp.type.modifier", c.gray, nil)
Group.new("@lsp.type.namespace", c.fg, nil)
Group.new("@lsp.type.number", c.blue, nil)
Group.new("@lsp.type.operator", c.yellow, nil)
Group.new("@lsp.type.parameter", c.fg, nil)
Group.new("@lsp.type.property", c.fg, nil)
Group.new("@lsp.type.selfKeyword", c.fg, nil)
Group.new("@lsp.type.selfTypeKeyword", c.fg, nil)
Group.new("@lsp.type.string", c.green, nil)
Group.new("@lsp.type.struct", c.yellow, nil)
Group.new("@lsp.type.type", c.blue, nil, s.underline)
Group.new("@lsp.type.typeParameter", c.blue, nil, s.italic)
Group.new("@lsp.type.variable", c.fg, nil)

-- Markdown
Group.new("markdownH1", c.blue, nil, s.bold)
Group.new("markdownH2", c.blue, nil, s.bold)
Group.new("markdownH3", c.blue, nil, s.bold)
Group.new("markdownH4", c.blue, nil, s.bold)
Group.new("markdownH5", c.blue, nil, s.bold)
Group.new("markdownH6", c.blue, nil, s.bold)
Group.new("markdownCode", c.green, nil)
Group.new("markdownCodeBlock", c.green, nil)
Group.new("markdownCodeDelimiter", c.green, nil)
Group.new("markdownLinkText", c.blue, nil, s.underline)
Group.new("markdownUrl", c.blue, nil, s.underline)
Group.new("markdownListMarker", c.gray, nil)
Group.new("markdownOrderedListMarker", c.gray, nil)
Group.new("markdownRule", c.nontext, nil)
Group.new("markdownHeadingDelimiter", c.fg_dim, nil)
Group.new("markdownLinkDelimiter", c.fg_dim, nil)
Group.new("markdownLinkTextDelimiter", c.fg_dim, nil)

-- Rainbow / Indent Blankline
Group.new("RainbowDelimiterRed", c.red, nil)
Group.new("RainbowDelimiterYellow", c.yellow, nil)
Group.new("RainbowDelimiterBlue", c.blue, nil)
Group.new("RainbowDelimiterGreen", c.green, nil)
Group.new("RainbowDelimiterViolet", c.purple, nil)
Group.new("RainbowDelimiterOrange", c.orange, nil)

Group.new("IblIndent", c.nontext, nil)
Group.new("IblScope", c.fg_dim, nil)

-- BufferLine
Group.new("BufferLineBackground", c.fg_dim, c.bg_alt)
Group.new("BufferLineBufferVisible", c.fg_muted, c.bg_alt)
Group.new("BufferLineBufferSelected", c.fg, c.bg)
Group.new("BufferLineIndicatorSelected", nil, c.bg)
Group.new("BufferLinePick", nil, nil, s.bold)
Group.new("BufferLinePickVisible", nil, nil, s.bold)
Group.new("BufferLineCloseButton", c.fg_dim, nil)
Group.new("BufferLineCloseButtonVisible", c.fg_dim, nil)
Group.new("BufferLineCloseButtonSelected", c.red_error, nil)
Group.new("BufferLineTab", c.fg_dim, c.bg_alt)
Group.new("BufferLineTabSelected", c.fg, c.bg)
Group.new("BufferLineTabClose", c.fg_dim, nil)
Group.new("BufferLineDuplicate", c.fg_dim, nil)
Group.new("BufferLineDuplicateSelected", c.fg_muted, nil)
Group.new("BufferLineDuplicateVisible", c.fg_dim, nil)
Group.new("BufferLineNumbers", c.fg_dim, nil)
Group.new("BufferLineNumbersSelected", c.fg_linenr_active, nil)
Group.new("BufferLineNumbersVisible", c.fg_dim, nil)
Group.new("BufferLineModified", c.yellow, nil)
Group.new("BufferLineModifiedSelected", c.yellow, nil)
Group.new("BufferLineModifiedVisible", c.yellow, nil)
Group.new("BufferLineError", c.red_error, nil)
Group.new("BufferLineErrorSelected", c.red_error, nil)
Group.new("BufferLineWarning", c.yellow, nil)
Group.new("BufferLineWarningSelected", c.yellow, nil)
Group.new("BufferLineHint", c.blue, nil)
Group.new("BufferLineHintSelected", c.blue, nil)
Group.new("BufferLineInfo", c.blue, nil)
Group.new("BufferLineInfoSelected", c.blue, nil)
Group.new("BufferLineSeparator", c.bg_border, c.bg_alt)
Group.new("BufferLineSeparatorSelected", c.bg_border, c.bg)
Group.new("BufferLineSeparatorVisible", c.bg_border, c.bg_alt)
Group.new("BufferLineOffsetSeparators", c.bg_border, c.bg_alt)
Group.new("BufferLineGroupBackground", c.fg_dim, c.bg_alt)
